# For save directories only enter the parent directory for all projects checkpoints. 
# project.name will be joined to both checkpoints and runs as the basename directory.


project:
    name:             'face_otherrace_white_asian'
    description:      'Training VGG on VGGFace using white and asian dataset'
    model:            'VGG16'
data_directories:
    task1:            '/raid/shared/datasets/visoin/data_face_white/'
    task2:            '/raid/shared/datasets/visoin/data_face_asian/'
save_directories:
    checkpoints_dir:  '/raid/shared/projects/face_otherrace_white_asian/checkpoints/vgg/'
    log_dir:          '/raid/shared/projects/face_otherrace_white_asian/runs/vgg/'
saving:
    keep:             [-1]
    function:         'step'
    params:           {'step': 1, 'offset': 0}
    max_count:        100
hyperparameters: 
    batch_size:       128
    optimizer:        'sgd'
    momentum:         0.9
    learning_rate:    0.001
    use_scheduler:    True
    scheduler:        'ReduceLROnPlateau'
    scheduler_params: {'patience': 5, 'verbose': True}
    weight_decay:     0.0001
    split:            False
max_train_samples:
    task1:            58
    task2:            58
max_valid_samples:
    task1:            5
    task2:            5
